hms-dbmi/pic-sure-all-in-one

initial-configuration/config/wildfly/standalone.xml
initial-configuration/jenkins/jenkins-docker/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Configure Outbound Email Settings/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml

allows configuration of a gmail account for outbound email transfer

Add email configuration job

---

initial-configuration/config/httpd/picsureui_settings.json
initial-configuration/jenkins/jenkins-docker/jobs/Project Specific PIC-SURE Overrides/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Start PIC-SURE/config.xml

move script execution to custom overrides job

update default settings to remove 'datastage'

---

initial-configuration/config/httpd/httpd-vhosts-ssloffload.conf
initial-configuration/config/setProxy.sh
initial-configuration/install-dependencies.sh
initial-configuration/jenkins/jenkins-docker/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Configure Outbound Email Settings/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Configure Proxy/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Configure SSLOffload/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Create PIC-SURE PassThrough Resource/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Load Genomic Data/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Load HPDS Data From RDBMS/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Auth Micro-App Build/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Database Migrations/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Wildfly Image Build/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE-API Build/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE-HPDS Build/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE-HPDS-UI Docker Build/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Project Specific PIC-SURE Overrides/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Start JupyterHub/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Start PIC-SURE/config.xml
initial-configuration/uninstall.sh
start-jenkins.sh
update-jenkins.sh

- Converted wildfly docker build to now rely on virtual deployments folder
- Updated pic-sure-api and pic-sure-auth to build/deploy to deployments folder
- New PassThrough resource build
- New Proxy Configuration build
- New SSL Offload configuration build

PassThrough Resource, Proxy, SSLOffload

---

README.md

Added JIRA Service Desk for contact. 
Fixed spelling mistake.

Streamline evaluation request

---

initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Database Migrations/config.xml

Each git repo will now pull it's appropriate git hash from the build spec

added build-spec git hashes

---

initial-configuration/jenkins/jenkins-docker/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Import Server Cert to TrustStore/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Load Genomic Metadata/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Passthrough Resource Pipeline/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Start PIC-SURE/config.xml
start-jenkins.sh
update-jenkins.sh

* add 'load genomic metadata' job
* add 'Passthrough Resource Pipeline' to use release control and automate certificate handling
* maintain same release control branch when updating jenkins
* add preset and unused DEBUG_OPTS and PROFILING_OPTS to ease debugging and profiling process

Jenkins updates

---

initial-configuration/install-dependencies.sh
initial-configuration/uninstall.sh

This PR is to switch to MariaDB from the community version of mysql

Switches to MariaDB from MySQL

---

initial-configuration/config/flyway/auth/flyway-auth.conf
initial-configuration/config/flyway/picsure/flyway-picsure.conf
initial-configuration/config/httpd/picsureui_settings.json
initial-configuration/jenkins/jenkins-docker/jobs/Check For Updates/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Database Migrations/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Database Repair/config.xml

Added database migrations to 'check for updates' job.  
Added logic to database migrations to better handle error cases.

Update check for updates

---

initial-configuration/jenkins/jenkins-docker/jobs/Start PIC-SURE/config.xml

Add option to override built-in connections.json for login control

update Start Pic-Sure

---

initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Aggregate Resource Build/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Build Passthrough Resource/config.xml

- Jenkins jobs for rebuilding Aggregate Resource and Passthrough resource
- Both of these jobs have initial build jobs that include a run-once SQL script
- These scripts just duplicate those jobs, sans SQL

[ALS-4771] - Jenkins jobs for rebuilding resources

---

README.md
initial-configuration/config/httpd/httpd-vhosts-ssloffload.conf
initial-configuration/config/httpd/httpd-vhosts.conf
initial-configuration/config/httpd/picsureui_settings.json
initial-configuration/jenkins/jenkins-docker/jobs/Configure Google Analytics/config.xml

[ALS-4884] Add new Jenkins Job to set Google analytics ID in the `picsureui_settings.json`.

[ALS-4884] Add Google Analytics job

---

initial-configuration/jenkins/jenkins-docker/jobs/Create PIC-SURE Aggregate Resource/config.xml

[ALS-4843] Configure obfuscation threshold to 0

---

README.md
initial-configuration/convert-cert.sh
initial-configuration/install-dependencies.sh
start-jenkins.sh

- Add script to enabel https in Jenkins
- Add documentation
- Add to initial config flow

[ALS-5060] Jenkins https

---

update-jenkins.sh

- We have run into this issue SO MANY TIMES
- Added a flag to rebuild Jenkins since it be slow

[ALS-0000] Rebuild Jenkins during update

---

initial-configuration/config/httpd/picsureui_settings.json
initial-configuration/jenkins/jenkins-docker/jobs/Configure Google Analytics/config.xml

[ALS-5151] Add Google Tag Manager

[ALS-5151] Add Google Tag Manager

---

initial-configuration/jenkins/jenkins-docker/jobs/Start PIC-SURE/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Stop PIC-SURE/config.xml
start-jenkins.sh

- Volume mount start, stop scripts to jenkins container
- Reference those scripts inside the jenkins jobs

[ALS-0000] De-duplicate start / stop logic

---

initial-configuration/config/httpd/banner_config.json
initial-configuration/jenkins/jenkins-docker/jobs/Update Banner Configuration/config.xml
start-picsure.sh

[ALS-5213] Additional job all-in-one infrastructure for banner config updates

[ALS-5213] Additional job all-in-one infrastructure for banner config updates

---

initial-configuration/install-dependencies.sh
initial-configuration/jenkins/jenkins-docker/jobs/Configure Institution Node/config.xml
initial-configuration/jenkins/jenkins-docker/plugins.yml

- Fix plugin versions
- Correct obfuscation threshold
- cd to correct dir before starting jenkins

[ALS-5906] Misc fixes found while doing fresh install

---

start-picsure.sh
update-jenkins.sh

- include a useful default value if the DOCKER_CONFIG_DIR environment variable isn't already set.

wustl update #1

---

initial-configuration/jenkins/jenkins-docker/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Build Dictionary API/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Deploy Dictionary API/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Pipeline/config.xml

- Build dict
- Deploy dict
- Add to c4u pipeline

[ALS-6725] Dictionary Devops

---

initial-configuration/jenkins/jenkins-docker/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Upload Dictionary .env File/config.xml
start-picsure.sh
stop-picsure.sh

- start changes
- stop changes
- upload env file

[ALS-6725] Dictionary Start / Stop + .env

---

initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Auth Micro-App Build/config.xml

Copy global maven settings to be used in container build

V2.5.0 changes

---

.gitignore
README.md
initial-configuration/jenkins/jenkins-docker/jobs/Create Root Certs in TrustStore/config.xml
initial-configuration/pass.tmp
start-picsure.sh

All-In-One: PSAMA to use its own trust store

All-In-One: PSAMA to use its own trust store

---

initial-configuration/jenkins/jenkins-docker/jobs/Start PIC-SURE/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Stop PIC-SURE/config.xml
start-jenkins.sh
start-picsure.sh

- Fixed it not working inside jenkins
- Refined the coupling between jenkins and bare metal script
- Make script exit with bad code if run commands fail

[ALS-7887] Start script improvements

---

initial-configuration/jenkins/jenkins-docker/jobs/Configure TOS/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Frontend Build/config.xml

- Add env variable to init config pipeline job.
- Add TOS copy job from TOS configuration workspace during frontend build.

[ALS-532] Add configuration job for TOS

---

initial-configuration/jenkins/jenkins-docker/jobs/Configure TOS/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml

- Default TOS env value to true on initial build.

Update Configure TOS job to copy the terms file only if the user has added one

---

initial-configuration/jenkins/jenkins-docker/jobs/Add Site to Passthrough Service/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/Build Passthru Image/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Dictionary API Build and Deploy/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Pipeline/config.xml
start-picsure.sh

- Build job for passthru
- Config modification job to add/modify sites
- Pipeline update to add passthru build to pipeline
- Fix to dictionary build when running

[ALS-8532] Passthru Devops

---

initial-configuration/jenkins/jenkins-docker/jobs/Migrate Dictionary Database/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Build Dictionary API/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Database Migrations/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Database Repair/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Dictionary API Build and Deploy/config.xml
start-picsure.sh

- Tweak start script
- Add Jobs to build, deploy, migrate dump dict

[ALS-8538] Devops for aggregate data dict

---

initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml
initial-configuration/mysql-docker/setup.sh
start-picsure.sh

- Inital config script put mysql conf in wrong location
- Misnamed dump to api
- Changed when we run migrations in initial config script

[CHORE] Clean up from all the breakages

---

initial-configuration/jenkins/jenkins-docker/Dockerfile
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Build and Deploy Uploader/config.xml
initial-configuration/jenkins/jenkins-docker/jobs/PIC-SURE Pipeline/config.xml

- Uploader deploy fixes to job and pipeline
- Fix to Jenkins Dockerfile to make docker install script more stable

[ALS-9177] Tuning for WashU test deploy
